language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      sudo: required
      dist: xenial

# command to install dependencies
install: "pip install ."
# command to run tests
script: nosetests --with-doctest

